export enum BillingAccountErrorCodes {
  NoBillingAccountCreated = 'billing_account.no_billing_account_created',
  BillingEntityFound = 'billing_account.billing_entity_found',
  NoBillingEntityCreated = 'billing_account.no_billing_entity_created',
  NoBillingAccountFound = 'billing_account.no_billing_account_found',
  NoBillingAccountFoundShield = 'billing_account.no_billing_account_found_shield',
  NoBillingAccountFoundBP = 'billing_account.no_billing_account_found_bp',
  InvalidBillingCompanyId = 'billing_account.invalid_billing_company_id',
  BillingAccountFailedShield = 'billing_account.billing_account_failed_shield',
  BillingAccountFailedBP = 'billing_account.billing_account_failed_bp',
  InvalidCustomerId = 'billing_account.invalid_customer_id',
  InvalidBillingAccount = 'billing_account.invalid_billing_account',
  ShieldAPITimeout = 'billing_account.shield_timeout',
  BpAPITimeout = 'billing_account.bp_timeout',
  InvalidCRMIds = 'billing_account.invalid_crm_ids',
  BillingEntityNotFound = 'billing_account.no_billing_entity_found',
  BillingAccountAssociatedWithBillingEntity = 'billing_account.billing_account_associated_with_billing_entity',
  NoBillingEntityUpdated = 'billing_account.no_billing_entity_updated',
  NoBillingEntityDeleted = 'billing_account.no_billing_entity_deleted',
  BillingAccountUpdateFailed = 'billing_account.billing_account_update_failed',
  SyncBillingAccountFailed = 'billing_account.sync_billing_account_failed',
  NoValidBillingAccountFound = 'billing_account.no_valid_billing_account_found',
  InvalidRequestBody = 'billing_account.invalid_request_body',
  BpDeleteCardFailed = 'billing_account.bp_delete_card_failed',
  BpCardNotFound = 'billing_account.bp_active_card_not_found',
}
