export enum IdentityErrorCodes {
  InvalidCompanyId = 'identity.invalid_companyid',
  InvalidEmail = 'identity.invalid_email',
  InvalidMongoId = 'identity.invalid_mongoid',
  InvalidUserId = 'identity.invalid_userid',
  InvalidEntityId = 'identity.invalid_entityid',
  InvalidRelationshipId = 'identity.invalid_relationshipid',
  InvalidUsername = 'identity.invalid_username',
  InvalidRelationshipDefinitionVerb = 'identity.invalid_relationship_definition_verb',
  InvalidEntityType = 'invalid_entity_type',
  UnsupportedDataSyncQuery = 'identity.unsupported_data_sync_query',
  UserNotFound = 'identity.user_not_found',
  CompanyNotFound = 'identity.company_not_found',
  RelationshipDefinitionNotFound = 'identity.relationship_definition_not_found',
  RelationshipDefinitionAlreadyExists = 'identity.relationship_definition_already_exists',
  RelationshipNotFound = 'identity.relationship_not_found',
  EmailExists = 'identity.email_exists',
  ProfileExists = 'identity.profile_exists',
  ProfileNotFound = 'identity.profile_not_found',
}
