import HttpStatusCodes from 'http-status-codes';

import { ErrorKey } from '../constants';

export const SubscriptionErrorParams = new Map<ErrorKey, number>([
  ['NoSubscriptionCreated', HttpStatusCodes.INTERNAL_SERVER_ERROR],
  ['NoBillingAccountCreated', HttpStatusCodes.EXPECTATION_FAILED],
  ['InvalidSubscriptionId', HttpStatusCodes.BAD_REQUEST],
  ['SubscriptionNotFound', HttpStatusCodes.NOT_FOUND],
  ['InvalidSubscriptionProductDetailsId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidSubscriptionProductAttributeDetailsId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidSubscriptionProductAttributeDetailsId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidOrderDisplayId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidProductOfferingId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidBaseProductOfferingId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidBillingAccountId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidServiceId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidOrderId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidPackageId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidProductId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidPackageProductId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidSubscription', HttpStatusCodes.INTERNAL_SERVER_ERROR],
  ['InvalidSubscriptionData', HttpStatusCodes.UNPROCESSABLE_ENTITY],
  ['InvalidCompanyName', HttpStatusCodes.BAD_REQUEST],
  ['InvalidCompanyId', HttpStatusCodes.BAD_REQUEST],
  ['InvalidOrderName', HttpStatusCodes.BAD_REQUEST],
  ['InvalidProductName', HttpStatusCodes.BAD_REQUEST],
  ['InvalidProcessInstanceId', HttpStatusCodes.BAD_REQUEST],
  ['PermissionDenied', HttpStatusCodes.FORBIDDEN],
  ['Unauthorized', HttpStatusCodes.UNAUTHORIZED],
  ['InvalidSubscription', HttpStatusCodes.BAD_REQUEST],
  ['InvalidUUIDSubscriptionProductMappingData', HttpStatusCodes.BAD_REQUEST],
  ['InvalidSubscriptionProductMappingData', HttpStatusCodes.BAD_REQUEST],
  ['SubscriptionProductMappingNotFound', HttpStatusCodes.NOT_FOUND],
  [
    'NoSubscriptionProductMappingCreated',
    HttpStatusCodes.INTERNAL_SERVER_ERROR,
  ],
  ['SubscriptionAttributeEnrichHandlerInvalid', HttpStatusCodes.BAD_REQUEST],
  ['InvalidOrderIdORSalesRecordId', HttpStatusCodes.BAD_REQUEST],
  ['InsightSubscriptionDetailNotFound', HttpStatusCodes.NOT_FOUND],
  ['InsightSubscriptionIdNotFound', HttpStatusCodes.NOT_FOUND],
  ['InvalidInsightSubscriptionData', HttpStatusCodes.BAD_REQUEST],
  ['NoInsightSubscriptionUpdated', HttpStatusCodes.INTERNAL_SERVER_ERROR],
  ['NoEnricherConfigUpdated', HttpStatusCodes.INTERNAL_SERVER_ERROR],
  ['SubscriptionEnricherConfigNotFound', HttpStatusCodes.NOT_FOUND],
  ['NoBodyFoundEnricherConfigUpdate', HttpStatusCodes.BAD_REQUEST],
  ['NoSubscriptionFetched', HttpStatusCodes.INTERNAL_SERVER_ERROR],
  ['SubscriptionAlreadyTerminated', HttpStatusCodes.BAD_REQUEST],
  ['InvalidSubscriptionAction', HttpStatusCodes.BAD_REQUEST],
]);
